### ISSUE TITLE
New Release Bookworm 9.1.5

### ISSUE THREAD

**Issue by rameister** [moode-player/docs#9]
The new Release Bookworm 9.1.5 that I've installed with PiImager on a SD-Card (8Gb) with the preconfigured User/WiFi/SSH on my Raspi 3B does not start. I see only the first colored Image on my Screen and it doesn't start. A next Image that I've done with Rufus shows the same. What's going wrong? Any idea?

**Comment by moodeaudio** [comment]
Questions and troubleshooting are handled in the Support section of our Forum so that all our users can benefit from the discussion.

Visit the Support page at moodeaudio.org for information on how to easily request a Forum account.
